[project]
name = "leetcode"
version = "0.1.0"
description = "KunteLin's LeetCode practice"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.14.11",
]
